# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ashkeys.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 388)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 182, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 95, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 199, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 182, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 95, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 199, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 182, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 95, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 481, 351))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_1 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.B1K_1 = QtGui.QPushButton(self.frame_1)
        self.B1K_1.setEnabled(False)
        self.B1K_1.setGeometry(QtCore.QRect(50, 130, 41, 32))
        self.B1K_1.setObjectName(_fromUtf8("B1K_1"))
        self.ticker_1 = QtGui.QLabel(self.frame_1)
        self.ticker_1.setGeometry(QtCore.QRect(40, 0, 121, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_1.sizePolicy().hasHeightForWidth())
        self.ticker_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_1.setFont(font)
        self.ticker_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_1.setObjectName(_fromUtf8("ticker_1"))
        self.qty_1 = QtGui.QLineEdit(self.frame_1)
        self.qty_1.setGeometry(QtCore.QRect(50, 50, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.qty_1.setPalette(palette)
        self.qty_1.setObjectName(_fromUtf8("qty_1"))
        self.SAll_1 = QtGui.QPushButton(self.frame_1)
        self.SAll_1.setEnabled(False)
        self.SAll_1.setGeometry(QtCore.QRect(50, 210, 41, 32))
        self.SAll_1.setObjectName(_fromUtf8("SAll_1"))
        self.SHalf_1 = QtGui.QPushButton(self.frame_1)
        self.SHalf_1.setEnabled(False)
        self.SHalf_1.setGeometry(QtCore.QRect(50, 170, 41, 32))
        self.SHalf_1.setObjectName(_fromUtf8("SHalf_1"))
        self.T_1 = QtGui.QLineEdit(self.frame_1)
        self.T_1.setGeometry(QtCore.QRect(50, 290, 100, 31))
        self.T_1.setObjectName(_fromUtf8("T_1"))
        self.label = QtGui.QLabel(self.frame_1)
        self.label.setGeometry(QtCore.QRect(10, 60, 31, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.frame_1)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 41, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.Arm = QtGui.QCheckBox(self.frame_1)
        self.Arm.setGeometry(QtCore.QRect(10, 10, 21, 23))
        self.Arm.setAutoFillBackground(True)
        self.Arm.setObjectName(_fromUtf8("Arm"))
        self.B2K_1 = QtGui.QPushButton(self.frame_1)
        self.B2K_1.setEnabled(False)
        self.B2K_1.setGeometry(QtCore.QRect(50, 90, 41, 32))
        self.B2K_1.setObjectName(_fromUtf8("B2K_1"))
        self.multiplier_1 = QtGui.QLineEdit(self.frame_1)
        self.multiplier_1.setGeometry(QtCore.QRect(50, 250, 100, 31))
        self.multiplier_1.setObjectName(_fromUtf8("multiplier_1"))
        self.label_5 = QtGui.QLabel(self.frame_1)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 41, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.SH2x_1 = QtGui.QPushButton(self.frame_1)
        self.SH2x_1.setEnabled(False)
        self.SH2x_1.setGeometry(QtCore.QRect(110, 90, 41, 32))
        self.SH2x_1.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.SH2x_1.setObjectName(_fromUtf8("SH2x_1"))
        self.SH1x_1 = QtGui.QPushButton(self.frame_1)
        self.SH1x_1.setEnabled(False)
        self.SH1x_1.setGeometry(QtCore.QRect(110, 130, 41, 32))
        self.SH1x_1.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.SH1x_1.setObjectName(_fromUtf8("SH1x_1"))
        self.BCh_1 = QtGui.QPushButton(self.frame_1)
        self.BCh_1.setEnabled(False)
        self.BCh_1.setGeometry(QtCore.QRect(110, 170, 41, 32))
        self.BCh_1.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.BCh_1.setObjectName(_fromUtf8("BCh_1"))
        self.BCa_1 = QtGui.QPushButton(self.frame_1)
        self.BCa_1.setEnabled(False)
        self.BCa_1.setGeometry(QtCore.QRect(110, 210, 41, 32))
        self.BCa_1.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.BCa_1.setObjectName(_fromUtf8("BCa_1"))
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame_2 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.ticker_2 = QtGui.QLabel(self.frame_2)
        self.ticker_2.setGeometry(QtCore.QRect(20, 0, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_2.sizePolicy().hasHeightForWidth())
        self.ticker_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_2.setFont(font)
        self.ticker_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_2.setObjectName(_fromUtf8("ticker_2"))
        self.qty_2 = QtGui.QLineEdit(self.frame_2)
        self.qty_2.setGeometry(QtCore.QRect(40, 50, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.qty_2.setPalette(palette)
        self.qty_2.setObjectName(_fromUtf8("qty_2"))
        self.T_2 = QtGui.QLineEdit(self.frame_2)
        self.T_2.setGeometry(QtCore.QRect(40, 290, 100, 31))
        self.T_2.setObjectName(_fromUtf8("T_2"))
        self.B2K_2 = QtGui.QPushButton(self.frame_2)
        self.B2K_2.setEnabled(False)
        self.B2K_2.setGeometry(QtCore.QRect(40, 90, 41, 32))
        self.B2K_2.setObjectName(_fromUtf8("B2K_2"))
        self.B1K_2 = QtGui.QPushButton(self.frame_2)
        self.B1K_2.setEnabled(False)
        self.B1K_2.setGeometry(QtCore.QRect(40, 130, 41, 32))
        self.B1K_2.setObjectName(_fromUtf8("B1K_2"))
        self.SHalf_2 = QtGui.QPushButton(self.frame_2)
        self.SHalf_2.setEnabled(False)
        self.SHalf_2.setGeometry(QtCore.QRect(40, 170, 41, 32))
        self.SHalf_2.setObjectName(_fromUtf8("SHalf_2"))
        self.SAll_2 = QtGui.QPushButton(self.frame_2)
        self.SAll_2.setEnabled(False)
        self.SAll_2.setGeometry(QtCore.QRect(40, 210, 41, 32))
        self.SAll_2.setObjectName(_fromUtf8("SAll_2"))
        self.multiplier_2 = QtGui.QLineEdit(self.frame_2)
        self.multiplier_2.setGeometry(QtCore.QRect(40, 250, 100, 31))
        self.multiplier_2.setObjectName(_fromUtf8("multiplier_2"))
        self.SH2x_2 = QtGui.QPushButton(self.frame_2)
        self.SH2x_2.setEnabled(False)
        self.SH2x_2.setGeometry(QtCore.QRect(100, 90, 41, 32))
        self.SH2x_2.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.SH2x_2.setObjectName(_fromUtf8("SH2x_2"))
        self.SH1x_2 = QtGui.QPushButton(self.frame_2)
        self.SH1x_2.setEnabled(False)
        self.SH1x_2.setGeometry(QtCore.QRect(100, 130, 41, 32))
        self.SH1x_2.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.SH1x_2.setObjectName(_fromUtf8("SH1x_2"))
        self.BCh_2 = QtGui.QPushButton(self.frame_2)
        self.BCh_2.setEnabled(False)
        self.BCh_2.setGeometry(QtCore.QRect(100, 170, 41, 32))
        self.BCh_2.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.BCh_2.setObjectName(_fromUtf8("BCh_2"))
        self.BCa_2 = QtGui.QPushButton(self.frame_2)
        self.BCa_2.setEnabled(False)
        self.BCa_2.setGeometry(QtCore.QRect(100, 210, 41, 32))
        self.BCa_2.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.BCa_2.setObjectName(_fromUtf8("BCa_2"))
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.ticker_3 = QtGui.QLabel(self.frame_3)
        self.ticker_3.setGeometry(QtCore.QRect(10, 0, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_3.sizePolicy().hasHeightForWidth())
        self.ticker_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_3.setFont(font)
        self.ticker_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_3.setObjectName(_fromUtf8("ticker_3"))
        self.qty_3 = QtGui.QLineEdit(self.frame_3)
        self.qty_3.setGeometry(QtCore.QRect(30, 50, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.qty_3.setPalette(palette)
        self.qty_3.setObjectName(_fromUtf8("qty_3"))
        self.T_3 = QtGui.QLineEdit(self.frame_3)
        self.T_3.setGeometry(QtCore.QRect(30, 290, 100, 31))
        self.T_3.setObjectName(_fromUtf8("T_3"))
        self.B2K_3 = QtGui.QPushButton(self.frame_3)
        self.B2K_3.setEnabled(False)
        self.B2K_3.setGeometry(QtCore.QRect(30, 90, 41, 32))
        self.B2K_3.setObjectName(_fromUtf8("B2K_3"))
        self.B1K_3 = QtGui.QPushButton(self.frame_3)
        self.B1K_3.setEnabled(False)
        self.B1K_3.setGeometry(QtCore.QRect(30, 130, 41, 32))
        self.B1K_3.setObjectName(_fromUtf8("B1K_3"))
        self.SHalf_3 = QtGui.QPushButton(self.frame_3)
        self.SHalf_3.setEnabled(False)
        self.SHalf_3.setGeometry(QtCore.QRect(30, 170, 41, 32))
        self.SHalf_3.setObjectName(_fromUtf8("SHalf_3"))
        self.SAll_3 = QtGui.QPushButton(self.frame_3)
        self.SAll_3.setEnabled(False)
        self.SAll_3.setGeometry(QtCore.QRect(30, 210, 41, 32))
        self.SAll_3.setObjectName(_fromUtf8("SAll_3"))
        self.multiplier_3 = QtGui.QLineEdit(self.frame_3)
        self.multiplier_3.setGeometry(QtCore.QRect(30, 250, 100, 31))
        self.multiplier_3.setObjectName(_fromUtf8("multiplier_3"))
        self.SH2x_3 = QtGui.QPushButton(self.frame_3)
        self.SH2x_3.setEnabled(False)
        self.SH2x_3.setGeometry(QtCore.QRect(90, 90, 41, 32))
        self.SH2x_3.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.SH2x_3.setObjectName(_fromUtf8("SH2x_3"))
        self.SH1x_3 = QtGui.QPushButton(self.frame_3)
        self.SH1x_3.setEnabled(False)
        self.SH1x_3.setGeometry(QtCore.QRect(90, 130, 41, 32))
        self.SH1x_3.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.SH1x_3.setObjectName(_fromUtf8("SH1x_3"))
        self.BCh_3 = QtGui.QPushButton(self.frame_3)
        self.BCh_3.setEnabled(False)
        self.BCh_3.setGeometry(QtCore.QRect(90, 170, 41, 32))
        self.BCh_3.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.BCh_3.setObjectName(_fromUtf8("BCh_3"))
        self.BCa_3 = QtGui.QPushButton(self.frame_3)
        self.BCa_3.setEnabled(False)
        self.BCa_3.setGeometry(QtCore.QRect(90, 210, 41, 32))
        self.BCa_3.setStyleSheet(_fromUtf8("background-color: rgb(80,40,40)"))
        self.BCa_3.setObjectName(_fromUtf8("BCa_3"))
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Etrade-HKey", None))
        self.B1K_1.setText(_translate("MainWindow", "B-1x", None))
        self.ticker_1.setText(_translate("MainWindow", "***", None))
        self.qty_1.setToolTip(_translate("MainWindow", "Quantity", None))
        self.SAll_1.setText(_translate("MainWindow", "S-a", None))
        self.SHalf_1.setText(_translate("MainWindow", "S-h", None))
        self.T_1.setToolTip(_translate("MainWindow", "Ticker", None))
        self.label.setText(_translate("MainWindow", "Qty", None))
        self.label_4.setText(_translate("MainWindow", "Sym", None))
        self.Arm.setText(_translate("MainWindow", "CheckBox", None))
        self.B2K_1.setText(_translate("MainWindow", "B-2x", None))
        self.multiplier_1.setToolTip(_translate("MainWindow", "Ticker", None))
        self.label_5.setText(_translate("MainWindow", "Xfact", None))
        self.SH2x_1.setText(_translate("MainWindow", "SH2x", None))
        self.SH1x_1.setText(_translate("MainWindow", "SH1x", None))
        self.BCh_1.setText(_translate("MainWindow", "BC-h", None))
        self.BCa_1.setText(_translate("MainWindow", "BC-a", None))
        self.ticker_2.setText(_translate("MainWindow", "***", None))
        self.B2K_2.setText(_translate("MainWindow", "B-2x", None))
        self.B1K_2.setText(_translate("MainWindow", "B-1x", None))
        self.SHalf_2.setText(_translate("MainWindow", "S-h", None))
        self.SAll_2.setText(_translate("MainWindow", "S-a", None))
        self.multiplier_2.setToolTip(_translate("MainWindow", "Ticker", None))
        self.SH2x_2.setText(_translate("MainWindow", "SH2x", None))
        self.SH1x_2.setText(_translate("MainWindow", "SH1x", None))
        self.BCh_2.setText(_translate("MainWindow", "BC-h", None))
        self.BCa_2.setText(_translate("MainWindow", "BC-a", None))
        self.ticker_3.setText(_translate("MainWindow", "***", None))
        self.B2K_3.setText(_translate("MainWindow", "B-2x", None))
        self.B1K_3.setText(_translate("MainWindow", "B-1x", None))
        self.SHalf_3.setText(_translate("MainWindow", "S-h", None))
        self.SAll_3.setText(_translate("MainWindow", "S-a", None))
        self.multiplier_3.setToolTip(_translate("MainWindow", "Ticker", None))
        self.SH2x_3.setText(_translate("MainWindow", "SH2x", None))
        self.SH1x_3.setText(_translate("MainWindow", "SH1x", None))
        self.BCh_3.setText(_translate("MainWindow", "BC-h", None))
        self.BCa_3.setText(_translate("MainWindow", "BC-a", None))

