# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hkeys.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(799, 432)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 182, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 95, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 199, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 182, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 95, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 199, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 222, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 182, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 95, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 71, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 391))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_1 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.Buy_1 = QtGui.QPushButton(self.frame_1)
        self.Buy_1.setEnabled(False)
        self.Buy_1.setGeometry(QtCore.QRect(50, 50, 100, 32))
        self.Buy_1.setObjectName(_fromUtf8("Buy_1"))
        self.ticker_1 = QtGui.QLabel(self.frame_1)
        self.ticker_1.setGeometry(QtCore.QRect(30, 0, 121, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_1.sizePolicy().hasHeightForWidth())
        self.ticker_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_1.setFont(font)
        self.ticker_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_1.setObjectName(_fromUtf8("ticker_1"))
        self.price_1 = QtGui.QPlainTextEdit(self.frame_1)
        self.price_1.setGeometry(QtCore.QRect(50, 130, 100, 31))
        self.price_1.setObjectName(_fromUtf8("price_1"))
        self.qty_1 = QtGui.QPlainTextEdit(self.frame_1)
        self.qty_1.setGeometry(QtCore.QRect(50, 90, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.qty_1.setPalette(palette)
        self.qty_1.setObjectName(_fromUtf8("qty_1"))
        self.SLimit_1 = QtGui.QPushButton(self.frame_1)
        self.SLimit_1.setEnabled(False)
        self.SLimit_1.setGeometry(QtCore.QRect(50, 170, 100, 32))
        self.SLimit_1.setObjectName(_fromUtf8("SLimit_1"))
        self.Sell_1 = QtGui.QPushButton(self.frame_1)
        self.Sell_1.setEnabled(False)
        self.Sell_1.setGeometry(QtCore.QRect(50, 290, 100, 32))
        self.Sell_1.setObjectName(_fromUtf8("Sell_1"))
        self.SLoss_1 = QtGui.QPushButton(self.frame_1)
        self.SLoss_1.setEnabled(False)
        self.SLoss_1.setGeometry(QtCore.QRect(50, 210, 100, 32))
        self.SLoss_1.setObjectName(_fromUtf8("SLoss_1"))
        self.loss_1 = QtGui.QPlainTextEdit(self.frame_1)
        self.loss_1.setGeometry(QtCore.QRect(50, 250, 100, 31))
        self.loss_1.setObjectName(_fromUtf8("loss_1"))
        self.T_1 = QtGui.QPlainTextEdit(self.frame_1)
        self.T_1.setGeometry(QtCore.QRect(50, 330, 100, 31))
        self.T_1.setObjectName(_fromUtf8("T_1"))
        self.label = QtGui.QLabel(self.frame_1)
        self.label.setGeometry(QtCore.QRect(10, 100, 31, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame_1)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 51, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame_1)
        self.label_3.setGeometry(QtCore.QRect(10, 260, 41, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame_1)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 41, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.Arm = QtGui.QCheckBox(self.frame_1)
        self.Arm.setGeometry(QtCore.QRect(10, 50, 21, 23))
        self.Arm.setAutoFillBackground(True)
        self.Arm.setObjectName(_fromUtf8("Arm"))
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame_2 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.Buy_2 = QtGui.QPushButton(self.frame_2)
        self.Buy_2.setEnabled(False)
        self.Buy_2.setGeometry(QtCore.QRect(20, 50, 100, 32))
        self.Buy_2.setObjectName(_fromUtf8("Buy_2"))
        self.ticker_2 = QtGui.QLabel(self.frame_2)
        self.ticker_2.setGeometry(QtCore.QRect(0, 0, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_2.sizePolicy().hasHeightForWidth())
        self.ticker_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_2.setFont(font)
        self.ticker_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_2.setObjectName(_fromUtf8("ticker_2"))
        self.price_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.price_2.setGeometry(QtCore.QRect(20, 130, 100, 31))
        self.price_2.setObjectName(_fromUtf8("price_2"))
        self.qty_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.qty_2.setGeometry(QtCore.QRect(20, 90, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.qty_2.setPalette(palette)
        self.qty_2.setObjectName(_fromUtf8("qty_2"))
        self.SLimit_2 = QtGui.QPushButton(self.frame_2)
        self.SLimit_2.setEnabled(False)
        self.SLimit_2.setGeometry(QtCore.QRect(20, 170, 100, 32))
        self.SLimit_2.setObjectName(_fromUtf8("SLimit_2"))
        self.Sell_2 = QtGui.QPushButton(self.frame_2)
        self.Sell_2.setEnabled(False)
        self.Sell_2.setGeometry(QtCore.QRect(20, 290, 100, 32))
        self.Sell_2.setObjectName(_fromUtf8("Sell_2"))
        self.SLoss_2 = QtGui.QPushButton(self.frame_2)
        self.SLoss_2.setEnabled(False)
        self.SLoss_2.setGeometry(QtCore.QRect(20, 210, 100, 32))
        self.SLoss_2.setObjectName(_fromUtf8("SLoss_2"))
        self.loss_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.loss_2.setGeometry(QtCore.QRect(20, 250, 100, 31))
        self.loss_2.setObjectName(_fromUtf8("loss_2"))
        self.T_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.T_2.setGeometry(QtCore.QRect(20, 330, 100, 31))
        self.T_2.setObjectName(_fromUtf8("T_2"))
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.Buy_3 = QtGui.QPushButton(self.frame_3)
        self.Buy_3.setEnabled(False)
        self.Buy_3.setGeometry(QtCore.QRect(20, 50, 100, 32))
        self.Buy_3.setObjectName(_fromUtf8("Buy_3"))
        self.ticker_3 = QtGui.QLabel(self.frame_3)
        self.ticker_3.setGeometry(QtCore.QRect(0, 0, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_3.sizePolicy().hasHeightForWidth())
        self.ticker_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_3.setFont(font)
        self.ticker_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_3.setObjectName(_fromUtf8("ticker_3"))
        self.price_3 = QtGui.QPlainTextEdit(self.frame_3)
        self.price_3.setGeometry(QtCore.QRect(20, 130, 100, 31))
        self.price_3.setObjectName(_fromUtf8("price_3"))
        self.qty_3 = QtGui.QPlainTextEdit(self.frame_3)
        self.qty_3.setGeometry(QtCore.QRect(20, 90, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.qty_3.setPalette(palette)
        self.qty_3.setObjectName(_fromUtf8("qty_3"))
        self.SLimit_3 = QtGui.QPushButton(self.frame_3)
        self.SLimit_3.setEnabled(False)
        self.SLimit_3.setGeometry(QtCore.QRect(20, 170, 100, 32))
        self.SLimit_3.setObjectName(_fromUtf8("SLimit_3"))
        self.Sell_3 = QtGui.QPushButton(self.frame_3)
        self.Sell_3.setEnabled(False)
        self.Sell_3.setGeometry(QtCore.QRect(20, 290, 100, 32))
        self.Sell_3.setObjectName(_fromUtf8("Sell_3"))
        self.SLoss_3 = QtGui.QPushButton(self.frame_3)
        self.SLoss_3.setEnabled(False)
        self.SLoss_3.setGeometry(QtCore.QRect(20, 210, 100, 32))
        self.SLoss_3.setObjectName(_fromUtf8("SLoss_3"))
        self.loss_3 = QtGui.QPlainTextEdit(self.frame_3)
        self.loss_3.setGeometry(QtCore.QRect(20, 250, 100, 31))
        self.loss_3.setObjectName(_fromUtf8("loss_3"))
        self.T_3 = QtGui.QPlainTextEdit(self.frame_3)
        self.T_3.setGeometry(QtCore.QRect(20, 330, 100, 31))
        self.T_3.setObjectName(_fromUtf8("T_3"))
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.Buy_4 = QtGui.QPushButton(self.frame_4)
        self.Buy_4.setEnabled(False)
        self.Buy_4.setGeometry(QtCore.QRect(20, 50, 100, 32))
        self.Buy_4.setObjectName(_fromUtf8("Buy_4"))
        self.ticker_4 = QtGui.QLabel(self.frame_4)
        self.ticker_4.setGeometry(QtCore.QRect(0, 0, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_4.sizePolicy().hasHeightForWidth())
        self.ticker_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_4.setFont(font)
        self.ticker_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_4.setObjectName(_fromUtf8("ticker_4"))
        self.price_4 = QtGui.QPlainTextEdit(self.frame_4)
        self.price_4.setGeometry(QtCore.QRect(20, 130, 100, 31))
        self.price_4.setObjectName(_fromUtf8("price_4"))
        self.qty_4 = QtGui.QPlainTextEdit(self.frame_4)
        self.qty_4.setGeometry(QtCore.QRect(20, 90, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.qty_4.setPalette(palette)
        self.qty_4.setObjectName(_fromUtf8("qty_4"))
        self.SLimit_4 = QtGui.QPushButton(self.frame_4)
        self.SLimit_4.setEnabled(False)
        self.SLimit_4.setGeometry(QtCore.QRect(20, 170, 100, 32))
        self.SLimit_4.setObjectName(_fromUtf8("SLimit_4"))
        self.Sell_4 = QtGui.QPushButton(self.frame_4)
        self.Sell_4.setEnabled(False)
        self.Sell_4.setGeometry(QtCore.QRect(20, 290, 100, 32))
        self.Sell_4.setObjectName(_fromUtf8("Sell_4"))
        self.SLoss_4 = QtGui.QPushButton(self.frame_4)
        self.SLoss_4.setEnabled(False)
        self.SLoss_4.setGeometry(QtCore.QRect(20, 210, 100, 32))
        self.SLoss_4.setObjectName(_fromUtf8("SLoss_4"))
        self.loss_4 = QtGui.QPlainTextEdit(self.frame_4)
        self.loss_4.setGeometry(QtCore.QRect(20, 250, 100, 31))
        self.loss_4.setObjectName(_fromUtf8("loss_4"))
        self.T_4 = QtGui.QPlainTextEdit(self.frame_4)
        self.T_4.setGeometry(QtCore.QRect(20, 330, 100, 31))
        self.T_4.setObjectName(_fromUtf8("T_4"))
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.Buy_5 = QtGui.QPushButton(self.frame_5)
        self.Buy_5.setEnabled(False)
        self.Buy_5.setGeometry(QtCore.QRect(20, 50, 100, 32))
        self.Buy_5.setObjectName(_fromUtf8("Buy_5"))
        self.ticker_5 = QtGui.QLabel(self.frame_5)
        self.ticker_5.setGeometry(QtCore.QRect(0, 0, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticker_5.sizePolicy().hasHeightForWidth())
        self.ticker_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.ticker_5.setFont(font)
        self.ticker_5.setAlignment(QtCore.Qt.AlignCenter)
        self.ticker_5.setObjectName(_fromUtf8("ticker_5"))
        self.price_5 = QtGui.QPlainTextEdit(self.frame_5)
        self.price_5.setGeometry(QtCore.QRect(20, 130, 100, 31))
        self.price_5.setObjectName(_fromUtf8("price_5"))
        self.qty_5 = QtGui.QPlainTextEdit(self.frame_5)
        self.qty_5.setGeometry(QtCore.QRect(20, 90, 100, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(73, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.qty_5.setPalette(palette)
        self.qty_5.setObjectName(_fromUtf8("qty_5"))
        self.SLimit_5 = QtGui.QPushButton(self.frame_5)
        self.SLimit_5.setEnabled(False)
        self.SLimit_5.setGeometry(QtCore.QRect(20, 170, 100, 32))
        self.SLimit_5.setObjectName(_fromUtf8("SLimit_5"))
        self.Sell_5 = QtGui.QPushButton(self.frame_5)
        self.Sell_5.setEnabled(False)
        self.Sell_5.setGeometry(QtCore.QRect(20, 290, 100, 32))
        self.Sell_5.setObjectName(_fromUtf8("Sell_5"))
        self.SLoss_5 = QtGui.QPushButton(self.frame_5)
        self.SLoss_5.setEnabled(False)
        self.SLoss_5.setGeometry(QtCore.QRect(20, 210, 100, 32))
        self.SLoss_5.setObjectName(_fromUtf8("SLoss_5"))
        self.loss_5 = QtGui.QPlainTextEdit(self.frame_5)
        self.loss_5.setGeometry(QtCore.QRect(20, 250, 100, 31))
        self.loss_5.setObjectName(_fromUtf8("loss_5"))
        self.T_5 = QtGui.QPlainTextEdit(self.frame_5)
        self.T_5.setGeometry(QtCore.QRect(20, 330, 100, 31))
        self.T_5.setObjectName(_fromUtf8("T_5"))
        self.horizontalLayout.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Etrade-HKey", None))
        self.Buy_1.setText(_translate("MainWindow", "Buy", None))
        self.ticker_1.setText(_translate("MainWindow", "***", None))
        self.price_1.setToolTip(_translate("MainWindow", "Price", None))
        self.qty_1.setToolTip(_translate("MainWindow", "Quantity", None))
        self.SLimit_1.setText(_translate("MainWindow", "Sell Limit", None))
        self.Sell_1.setText(_translate("MainWindow", "Sell", None))
        self.SLoss_1.setText(_translate("MainWindow", "Stop loss", None))
        self.loss_1.setToolTip(_translate("MainWindow", "Stop loss $", None))
        self.T_1.setToolTip(_translate("MainWindow", "Ticker", None))
        self.label.setText(_translate("MainWindow", "Qty", None))
        self.label_2.setText(_translate("MainWindow", "$Lim", None))
        self.label_3.setText(_translate("MainWindow", "$top", None))
        self.label_4.setText(_translate("MainWindow", "Sym", None))
        self.Arm.setText(_translate("MainWindow", "CheckBox", None))
        self.Buy_2.setText(_translate("MainWindow", "Buy", None))
        self.ticker_2.setText(_translate("MainWindow", "***", None))
        self.SLimit_2.setText(_translate("MainWindow", "Sell Limit", None))
        self.Sell_2.setText(_translate("MainWindow", "Sell", None))
        self.SLoss_2.setText(_translate("MainWindow", "Stop loss", None))
        self.Buy_3.setText(_translate("MainWindow", "Buy", None))
        self.ticker_3.setText(_translate("MainWindow", "***", None))
        self.SLimit_3.setText(_translate("MainWindow", "Sell Limit", None))
        self.Sell_3.setText(_translate("MainWindow", "Sell", None))
        self.SLoss_3.setText(_translate("MainWindow", "Stop loss", None))
        self.Buy_4.setText(_translate("MainWindow", "Buy", None))
        self.ticker_4.setText(_translate("MainWindow", "***", None))
        self.SLimit_4.setText(_translate("MainWindow", "Sell Limit", None))
        self.Sell_4.setText(_translate("MainWindow", "Sell", None))
        self.SLoss_4.setText(_translate("MainWindow", "Stop loss", None))
        self.Buy_5.setText(_translate("MainWindow", "Buy", None))
        self.ticker_5.setText(_translate("MainWindow", "***", None))
        self.SLimit_5.setText(_translate("MainWindow", "Sell Limit", None))
        self.Sell_5.setText(_translate("MainWindow", "Sell", None))
        self.SLoss_5.setText(_translate("MainWindow", "Stop loss", None))

